version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major:
        update-types:
          - "major"
      minor:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major:
        update-types:
          - "major"
      minor:
        patterns:
          - "*"
